### PR TITLE
Added MustNewAESTransformer

### PR DESCRIPTION
**Pull request by ryanskidmore**
Added a function to force the creation of an AES Transformer, else application panics. I've added this to satisfy the MustNewServer() function in GoWork, which requires a non error returning function.

This will allow this library to be implemented into GoWork with minimal changes to GoWork.

### CODE REVIEW

**Comment by peter-edge** [comment]
Hey Ryan,

My apologies for not getting back to you on the PR in GoWork! I have been extremely busy.

So per normal golang idioms, panic should only happen if there is really a problem where you cannot continue the program, i.e. a nil pointer, for example. Trying to find some good articles but my googling ability is failing me today.

Adding panics like this to a library results in unexpected behavior for other users that violates this golang idiom - I would recommend if you want to do this, just do it in your code. However, I would recommend designing such code to not panic, but to gracefully handle an error.

Short: if you want to do this, just make this a wrapper function in GoWork. BUT, I recommend against panicking in the first place :)

**Comment by ryanskidmore** [comment]
Hm, okay.

My intention was that by having this optional additional function, applications which would require a transformer to be created (such as GoWork) could do so, since GoWork is essentially useless if that transformer cannot be created - hence a reason to panic.

Let me know what you think

**Comment by peter-edge** [comment]
I would just add this to GoWork instead of here - I really stick by the non-panic idiom :) I can add it to GoWork if you want.

**Comment by ryanskidmore** [comment]
Sure, feel free to close this and put it in your existing GoWork PR - I mirrored your changes locally and it all seems to work :)

**Comment by peter-edge** [comment]
Sweet, you got it, just updated the GoWork branch, will add this method :)

**Pull request closed without merging**
